name: Build libnode

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build xmake project
        shell: bash
        run: xmake -y --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libnode-${{ runner.os }}-${{ matrix.arch }}
          path: ./artifacts

      - name: Run test
        shell: bash
        run: xmake run
