name: Build libnode

on:
  push:
    tags:        
      - release

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - uses: jirutka/setup-alpine@v1
        if: runner.os != 'Windows'
        with:
          branch: v3.15

      - name: Build project
        if: runner.os != 'Windows'
        shell: alpine.sh {0}
        run: ./build.sh

      - name: Build project
        if: runner.os == 'Windows'
        run: build.bat

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libnode-${{ runner.os }}-${{ matrix.arch }}
          path: ./node/out/Release

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/libnode-Windows-x64/libnode20.dll
            ${{ github.workspace }}/libnode-Windows-x64/libnode20.lib
            ${{ github.workspace }}/libnode-Windows-x64/libnode20.pdb
            ${{ github.workspace }}/libnode-Linux-x64/libnode20.so

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: libnode-*

