name: Build libnode

on:
  push:
    tags:        
      - release
      - debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build xmake project
        if: runner.os != 'Windows'
        shell: bash
        run: | 
            xmake config -y -m ${{  github.ref_name }} --verbose
            xmake -y --verbose

      - name: Build xmake project
        if: runner.os == 'Windows'
        shell: bash
        run: | 
            xmake config -y -p windows -m ${{  github.ref_name }} --toolchain=msvc --verbose
            xmake -y --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libnode-${{ runner.os }}-${{ matrix.arch }}
          path: ./artifacts

  release:
    runs-on: ubuntu-latest
    needs: build
    permissions: 
      contents: write
    steps:
      - name: Download artifacts
        uses: dawidd6/action-download-artifact@v3
        skip_unpack: true
        path: ${{ github.workspace }}

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ${{ github.workspace }}/libnode-Linux-x64.zip
            ${{ github.workspace }}/libnode-Windows-x64.zip

      - name: Delete artifacts
        uses: geekyeggo/delete-artifact@v5
        with:
          name: libnode-*

