name: Build libnode

on:
  push:
    tags:        
      - release
      - debug

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        arch: [x64]
        os: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup xmake
        uses: xmake-io/github-action-setup-xmake@v1
        with:
          xmake-version: latest

      - name: Build xmake project
        if: runner.os != 'Windows'
        shell: bash
        run: | 
            xmake config -y -m ${{  github.ref_name }}
            xmake -y --verbose

      - name: Build xmake project
        if: runner.os == 'Windows'
        shell: bash
        run: | 
            xmake config -y -p windows -m ${{  github.ref_name }} --toolchain=msvc --verbose
            xmake -y --verbose

      - name: Upload artifacts
        uses: actions/upload-artifact@v2.3.1
        with:
          name: libnode-${{ runner.os }}-${{ matrix.arch }}
          path: ./artifacts
